- name: Create Jenkins Jobs
  hosts: localhost
  connection: local
  vars:
    jobs:
      - roboshop-terraform
      - cart
      - catalogue
      - user
      - shipping
      - payment
      - frontend
#  vars:
#    sp_jobs:
#      - roboshop-terraform
#      - roboshop-ansible
#      - roboshop-kubernetes
#    mp_jobs:

#      - aws-parameter-init-container
#      - schema-load-init-container
  roles:
    - jenkins-jobs